USE VENDA
--RECAPTULANDO AULA PASSADA
SELECT AVG (SALARIO) AS SALARIO_VENDEDOR FROM VENDEDOR;

SELECT MAX (SALARIO) AS SALARIO_VENDEDOR FROM VENDEDOR;

SELECT COUNT (MATRICULA) AS QUANTIDADE FROM VENDEDOR;

SELECT COUNT (*) AS QUANTIDADE FROM VENDEDOR;

SELECT * FROM VENDEDOR;

--EXPRESSÕES ARITIMÉTICAS
SELECT NOME, SALARIO * 1.05 AS SALARIO_NOVO FROM VENDEDOR;

--ATUALIZAR SALÁRIO DO VENDEDOR
UPDATE VENDEDOR
SET SALARIO = SALARIO + (SALARIO * 0.1)
WHERE NOME = 'NATHAN DANTAS';


--ADICIONAR CLIENTES NA TABELA
SELECT * FROM CLIENTE;

INSERT INTO CLIENTE
VALUES (104, 'JOSÉ CARLOS', '11121313313', 1212313131, 'VILA MARIANA', 'SÃO PAULO', 'DA SILVA'),
		(105, 'EDUARDO', '13131341313', 0986441233, 'ZONA NORTE', 'SÃO PAULO', 'NARDONI'),
		(106, 'ELIEL', '97652342531', 0921213133, 'VILA DAS BELEZAS', 'SÃO PAULO', 'ANDRADE');

--EXEMPLO DE AUTO-INCREMENTO
CREATE TABLE TESTE (
	COD_TESTE INT NOT NULL PRIMARY KEY IDENTITY (1000, 1),
	NOME VARCHAR (20) NOT NULL);

INSERT INTO TESTE
	VALUES	('TESTE 1'),
			('TESTE 2'),
			('TESTE 3'),
			('TESTE 4');

SELECT * FROM TESTE;

--SUB CONSULTA
SELECT * FROM CLIENTE
--LISTAR OS CLIENTES QUE RESIDEM NA MESMA CIDADE QUE O PEDRO
SELECT NOME FROM CLIENTE WHERE NOME <> 'PEDRO'
AND CIDADE IN (SELECT CIDADE FROM CLIENTE WHERE NOME = 'PEDRO');

--BUSCANDO USANDO NULL
--BUSCAR CLIENTES QUE ESTÃO COM O CAMPO SOBRENOME NULO
SELECT NOME FROM CLIENTE 
WHERE SOBRENOME IS NULL;

--BUSCAR CLIENTES QUE ESTÃO COM O CAMPO SOBRENOME PREENCHIDO
SELECT NOME FROM CLIENTE 
WHERE SOBRENOME IS NOT NULL;

SELECT * FROM PRODUTO;
SELECT * FROM PRATELEIRA;

INSERT INTO PRATELEIRA
VALUES (2, 'SUL', 'PERIFÉRICOS'),
		(3, 'SUL', 'PERIFÉRICOS');

UPDATE PRATELEIRA
SET SETOR = 'COMPUTADORES'
WHERE SETOR = 'CONGELADOS';

DELETE PRODUTO WHERE COD_PRODUTO = 1;


INSERT INTO PRODUTO 
	VALUES (11, 'COMPUTADOR', 'DELL', 1000.00, 1),
		  (12, 'TECLADO', 'HP', 100.00, 2),
		  (13, 'MOUSE', 'DELL', 50.00, 3);

SELECT * FROM VENDA;

INSERT INTO ITEM_VENDA
VALUES (100, 127, 11),
	  (101, 127, 12),
	  (102, 128, 13),
	  (103, 128, 12),
	  (104, 128, 12),
	  (105, 129, 11),
	  (106, 129, 11);

--AGRUPAMENTO - GROUP BY - SELECT
--PARA CADA VENDEDOR LISTAR O NOME E TOTAL DE CADA VENDA FEITA POR ELE
SELECT VD.NOME, SUM (P.VALOR) AS VALOR_VENDA FROM VENDEDOR VD, PRODUTO P, VENDA V, ITEM_VENDA I
WHERE VD.MATRICULA = V.MATRICULA
AND V.COD_VENDA = I.COD_VENDA
AND I.COD_PRODUTO = P.COD_PRODUTO
GROUP BY VD.NOME
HAVING SUM (P.VALOR) > 1000;

